FROM node:19-alpine As development

WORKDIR /usr/src/app

COPY worker-orders ./

RUN npm install

RUN npm run build
# RUN npm run build billings --prefix service-gw

FROM node:alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "worker-orders/dist/main"]