services:
  orders:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./service-gw/Dockerfile
      target: development
    command: npm run start:dev
    # env_file:
    #   - ./service-gw/.env
    volumes:
      - ./service-gw:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
